### ISSUE TITLE
Losing few seconds of audio every 5 minutes

### ISSUE THREAD

**Issue by jinyeng** [aws-samples/aws-transcribe-streaming-example-java#12]
When running this sample . every 5 minutes following message shows up. And when session restarts it loses about 10 seconds of audio transcription. This is unaaceptable for any realtime production application. Can signature expiration be set to larget than 5 minutes ? I see that max allowed value is 5 minutes.

java.util.concurrent.CompletionException: software.amazon.awssdk.services.transcribestreaming.model.BadRequestException: Signature expired: 20200122T184650Z is now earlier than 20200122T184650Z (20200122T185150Z - 5 min.)

**Comment by nvbkdw** [comment]
@jinyeng what kind of credential did you used to sign streaming request?

**Comment by groverkaran11** [comment]
@jinyeng We have updated the Transcribe Streaming SDK and the error you get should be fixed with this. Please reopen if the issue persists.

**Comment by ranman** [comment]
@groverkaran11 can you let us know what version of the java SDK we should use to fix this issue? Do you have any more details on what the issue was and how it started happening?

**Comment by boopathikumar018** [comment]
Hi @ranman update the SDK version to 'software.amazon.awssdk:transcribestreaming:2.7.27' to fix the issue
